name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
    
    - name: Build and Run Playwright Tests
      run: |
        cd StrumPlatform  # Change to your project's root directory
        mvn clean test  # Change to the Maven command you use to run your Playwright tests

